### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by stephen9999999** [LeiXu1999/EPLF-VINS#1]
Hi, thanks for your great work.
May I ask when will the source code be released?

**Comment by LeiXu1999** [comment]
I'm busy getting my master's degree now, and the open source version is being prepared as soon as possible. I'm sorry I haven't been able to open source it yet. An open source version of the algorithm will be released no later than August!!

**Comment by LeiXu1999** [comment]
An open source version of the algorithm has been released. Thanks for support and attention.
